str1 = input('请输入第一个字符串：')
str2 = input('请输入第二个字符串：')
str3 = input('请输入第三个字符串：')

maxStr = max(len(str1),len(str2),len(str3))
#print(maxStr)
print('+'+'-'*maxStr+'+')
print('| '+str1.center(maxStr)+' |')
print('| '+str2.center(maxStr)+' |')
print('| '+str3.center(maxStr)+' |')
print('+'+'-'*maxStr+'+')